export const API_URL = "http://localhost:8081/api";

export const API_PATH = {
  SIGN_UP: "/sign-up",
  SIGN_IN: "/login",
  NEW_WALLET: "/wallet/new",
  NEW_SAVING_ACCOUNT: "/wallet/new-saving-account",
  GET_ALL_WALLETS: "/wallet/get-all",
  NEW_CATEGORY: "/category/new",
  GET_ALL_EXPENSE_CATEGORIES: "/category/get-all-expense",
  GET_ALL_INCOME_CATEGORIES: "/category/get-all-income",
  EDIT_CATEGORY: "/category/update",
  DELETE_CATEGORY: "/category/delete",
  NEW_EXPENSE_INCOME: "/expense-income/new",
  NEW_LIMIT_EXPENSE: "/limit-expense/new",
  DELETE_LIMIT_EXPENSE: "/limit-expense/delete",
  GET_ALL_LIMIT_EXPENSE: "/limit-expense/get-all",
  NEW_RECURRING_TRANSACTION: "/recurring-transaction/new",
  GET_ALL_RECURRING_TRANSACTION: "/recurring-transaction/get-all",
  EDIT_RECURRING_TRANSACTION: "/recurring-transaction/update",
  DELETE_RECURRING_TRANSACTION: "/recurring-transaction/delete",
  GET_ALL_USER_DEBT_INFO: "/user-debt-info/get-all",
  NEW_DEBT_INFO: "/debt/new",
  STATISTIC_GENERAL: "/statistic/general",
  STATISTIC_EXPENSE_INCOME_GRAPH: "/statistic/expense-income-graph",
  STATISTIC_EXPENSE_GRAPH: "/statistic/expense-graph",
  STATISTIC_INCOME_GRAPH: "/statistic/income-graph",
  DEBT_GET_ALL_BORROW: "/debt/get-all-borrow",
  DEBT_GET_ALL_LEND: "/debt/get-all-lend",
  DEBT_DELETE_BY_USER_DEBT_INFO_NO: "/debt/delete-by-user",
  GET_ALL_NOTIFICATION: "/notification/get-all",
  READ_NOTIFICATION: "/notification/is-read"
}